package com.example.ronglinbo.mymvp.db.greendao.dao;



import com.example.ronglinbo.mymvp.en.LocalCacheDateInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localCacheDateInfoDaoConfig;


    private final LocalCacheDateInfoDao localCacheDateInfoDao;


    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localCacheDateInfoDaoConfig = daoConfigMap.get(LocalCacheDateInfoDao.class).clone();
        localCacheDateInfoDaoConfig.initIdentityScope(type);



        localCacheDateInfoDao = new LocalCacheDateInfoDao(localCacheDateInfoDaoConfig, this);


        registerDao(LocalCacheDateInfo.class, localCacheDateInfoDao);

    }
    
    public void clear() {
        localCacheDateInfoDaoConfig.clearIdentityScope();
    }

    public LocalCacheDateInfoDao getLocalCacheDateInfoDao() {
        return localCacheDateInfoDao;
    }



}
